##########################################################
###################  生产环境的profile  ###################
##########################################################
spring:
  profiles: prod
  datasource:
      url: jdbc:mysql://10.10.10.2:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: Nihaoccj123
      filters: log4j,wall,mergeStat

logging:
  level.root: warn
  path: logs

